create table if not exists public.survey_responses (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default timezone('utc', now()),
  age text,
  gender text,
  school text,
  degree text,
  year text,
  major text,
  favorite_status text,
  favorite_roles jsonb not null default '[]'::jsonb,
  role_reasons jsonb not null default '[]'::jsonb,
  role_follow text,
  role_buy text,
  role_actions jsonb not null default '[]'::jsonb,
  fan_watch text,
  fan_types jsonb not null default '[]'::jsonb,
  fan_frequency text,
  fan_platforms jsonb not null default '[]'::jsonb,
  fan_reasons jsonb not null default '[]'::jsonb,
  fan_interactions jsonb not null default '[]'::jsonb,
  create_status text,
  create_types jsonb not null default '[]'::jsonb,
  create_motivations jsonb not null default '[]'::jsonb,
  importance_scores jsonb not null default '{}'::jsonb,
  important_text text,
  keep_content text
);

alter table public.survey_responses enable row level security;

drop policy if exists "anonymous users can submit surveys" on public.survey_responses;
create policy "anonymous users can submit surveys"
  on public.survey_responses for insert
  to anon, authenticated
  with check (true);
