import React, {useMemo, useState} from 'react'
import {createRoot} from 'react-dom/client'
import './styles.css'
import {supabase} from './lib/supabase'

const scale = ['非常不同意','不同意','一般','同意','非常同意']
const importanceGroups = [
 ['娱乐与日常功能',['二次元是我日常生活中重要的娱乐方式。','我每天都会接触某种二次元内容。','二次元兴趣已经成为我的生活习惯。','如果一段时间无法接触二次元，我会感到不适应。','二次元占据了我大量的闲暇时间。']],
 ['情绪与心理功能',['二次元内容能帮助我缓解压力。','二次元内容能在我情绪低落时安慰我。','我会通过二次元内容逃避现实中的烦恼。','二次元作品或角色曾在困难时期陪伴过我。','二次元给我提供了现实生活中难以获得的情绪体验。','我会因为作品、角色或圈内事件产生强烈情绪波动。']],
 ['身份认同功能',['二次元是我认识自己的一部分。','我认为“二次元爱好者”是我的重要身份之一。','我会用二次元兴趣来描述自己。','我希望别人了解并认可我的二次元兴趣。','我会因为二次元兴趣与其他人产生亲近感。','即使未来接触时间减少，我仍然会认为自己属于二次元群体。']],
 ['社交与归属功能',['二次元让我认识了现实生活中的朋友。','二次元社群让我感到自己有归属感。','我在二次元社群中比在普通社交环境中更容易表达自己。','我会因为朋友或社群成员而继续关注二次元。','如果没有二次元社群，我的生活会少一部分重要的人际关系。','我更重视二次元圈子中的人际关系，而不是单独观看作品。']],
 ['现实生活影响',['二次元兴趣提高了我的生活质量。','二次元兴趣帮助我形成了某些技能或能力。','二次元兴趣影响过我的学习安排。','二次元兴趣影响过我的作息。','二次元消费影响过我的生活支出。','我能够较好地平衡二次元兴趣与学习生活。','即使二次元对生活有一定影响，我仍认为这种影响总体值得。']],
 ['作品与圈层重要性',['对我来说，最重要的是作品本身的内容。','对我来说，最重要的是喜欢的角色。','对我来说，最重要的是与其他人的共同话题。','对我来说，最重要的是二次元社群带来的归属感。','对我来说，最重要的是参与创作和表达。','即使没有社群和朋友，我仍会继续喜欢二次元作品。','即使没有特别喜欢的作品，我仍愿意留在二次元圈子中。']]
]
const checkGroups={roleReasons:['性格特点','外貌或设计','故事经历','价值观或处事方式','与角色产生情感共鸣','角色成长过程','配音、声优或表演','角色与其他人物的关系','角色带来的陪伴感','角色具有理想化特质','受到朋友或社群影响'], roleActions:['观看其所属作品','补完相关系列作品','搜索角色资料','观看角色剪辑或二次创作','购买周边','参加相关活动','进行角色模仿、Cosplay或创作','与其他粉丝交流'], fanTypes:['同人绘画','同人漫画','同人小说','剪辑视频','混剪、MAD或AMV','搞笑、鬼畜或恶搞视频','配音、广播剧或剧情演绎','翻唱','舞蹈或宅舞','Cosplay照片或视频','角色模仿','二创游戏、MOD或地图','粘土、手办、模型等实体创作','手工、服装或道具制作','粉丝理论、考据和剧情解析','同人音乐','AI辅助生成的二创内容'], platforms:['哔哩哔哩','抖音','快手','微博','小红书','LOFTER','半次元或类似平台','贴吧、论坛或兴趣社区','QQ群、微信群或Discord等社群','Steam创意工坊或游戏平台','漫展、同人展等线下活动'], interactions:['点赞','收藏','转发','评论','关注创作者','加入相关社群','参与话题讨论','打赏或付费支持','自己进行再创作','只观看，不进行互动'], createTypes:['绘画','写作','视频剪辑','配音','翻唱','舞蹈','Cosplay','摄影','模型、手工或道具','游戏、MOD或程序','音乐'], motivations:['表达对原作或角色的喜爱','表达个人观点','练习创作技能','与他人交流','获得关注或认可','记录个人情绪','参与社群活动','尝试获得收入']}
function App(){
 const [data,setData]=useState({consent:'',student:'',age:'',gender:'',school:'',degree:'',year:'',major:'',fav:'',roles:[{name:'',work:''},{name:'',work:''},{name:'',work:''}],watch:'',create:'',importance:{}})
 const [submitted,setSubmitted]=useState(false)
 const set=(k,v)=>setData(d=>({...d,[k]:v})); const toggle=(group,v)=>setData(d=>({...d,[group]:((d[group]||[]).includes(v)?d[group].filter(x=>x!==v):[...(d[group]||[]),v])}));
 const updateRole=(i,k,v)=>setData(d=>({...d,roles:d.roles.map((r,j)=>j===i?{...r,[k]:v}:r)}))
 const submit=async e=>{
  e.preventDefault()
  if(!supabase){window.alert('问卷暂未配置数据库连接，请联系调查发起人。');return}
  const {error}=await supabase.from('survey_responses').insert({
   age:data.age,gender:data.gender,school:data.school,degree:data.degree,year:data.year,major:data.major,
   favorite_status:data.fav,favorite_roles:data.roles,role_reasons:data.roleReasons||[],role_follow:data.roleFollow,role_buy:data.roleBuy,role_actions:data.roleActions||[],
   fan_watch:data.watch,fan_types:data.fanTypes||[],fan_frequency:data.watchFreq,fan_platforms:data.platforms||[],fan_reasons:data.watchReasons||[],fan_interactions:data.interactions||[],
   create_status:data.create,create_types:data.createTypes||[],create_motivations:data.motivations||[],importance_scores:data.importance,important_text:data.importantText,keep_content:data.keep
  })
  if(error){window.alert('提交失败，请稍后重试。');return}
  setSubmitted(true);window.scrollTo({top:0,behavior:'smooth'})
 }
 if(submitted)return <main className="survey-shell"><div className="success"><span className="eyebrow">调查已提交</span><h1>感谢你的参与。</h1><p>你的回答将以匿名形式用于大学生二次元群体相关议题的社会调研。</p><button className="primary" onClick={()=>setSubmitted(false)}>返回查看问卷</button></div></main>
 return <main className="survey-shell"><header className="survey-header"><div><span className="eyebrow">FIELD STUDY / 2026</span><h1>大学生二次元生活与社群调查</h1><p>面向中国大陆高校在校生的匿名社会调查，预计用时10—15分钟。</p></div><div className="badge">ANONYMOUS<br/>RESEARCH</div></header><form onSubmit={submit}>
 <Section title="一、筛选与基本信息"><Radio label="1. 你是否为中国大陆高校在校学生？" value={data.student} onChange={v=>set('student',v)} options={['是','否']} required/><Radio label="2. 你的年龄" value={data.age} onChange={v=>set('age',v)} options={['18岁','19岁','20岁','21岁','22岁','23岁','24—30岁']} required/><Radio label="3. 你是否愿意匿名参加本调查？" value={data.consent} onChange={v=>set('consent',v)} options={['愿意','不愿意']} required/><Radio label="4. 你的性别" value={data.gender} onChange={v=>set('gender',v)} options={['男','女','非二元或其他','不便回答']}/><Radio label="5. 学校类型" value={data.school} onChange={v=>set('school',v)} options={['高职高专','普通本科','重点本科或“双一流”高校','民办本科','其他']}/><Radio label="6. 当前学历" value={data.degree} onChange={v=>set('degree',v)} options={['专科','本科','硕士研究生','博士研究生','其他']}/><Radio label="7. 当前年级" value={data.year} onChange={v=>set('year',v)} options={['大一','大二','大三','大四或大五','研一','研二及以上']}/><Input label="8. 所学专业" value={data.major} onChange={v=>set('major',v)} placeholder="例如：计算机科学与技术"/></Section>
 <Section title="二、角色偏好"><Radio label="9. 你是否有明确喜欢的二次元角色或“本命”？" value={data.fav} onChange={v=>set('fav',v)} options={['有一个','有多个','曾经有过，现在没有','没有','不确定']} required/>{(data.fav==='有一个'||data.fav==='有多个')&&<div className="conditional"><p className="hint">请填写最多3个对你最重要的角色，可填写常用称呼。</p>{data.roles.map((r,i)=><div className="role-row" key={i}><Input label={`角色${i+1}`} value={r.name} onChange={v=>updateRole(i,'name',v)} placeholder="角色名称"/><Input label="所属作品（可选）" value={r.work} onChange={v=>updateRole(i,'work',v)} placeholder="作品名称"/></div>)}<Checks label="10. 你喜欢这些角色的主要原因（可多选）" items={checkGroups.roleReasons} group="roleReasons" data={data} toggle={toggle}/><Radio label="11. 你是否会持续关注喜欢角色的相关内容？" value={data.roleFollow} onChange={v=>set('roleFollow',v)} options={['经常','偶尔','很少','几乎不会']}/><Radio label="12. 你是否购买过喜欢角色的相关商品或数字内容？" value={data.roleBuy} onChange={v=>set('roleBuy',v)} options={['经常购买','偶尔购买','曾经购买过','从未购买']}/><Checks label="13. 你是否会因为喜欢某个角色而（可多选）" items={checkGroups.roleActions} group="roleActions" data={data} toggle={toggle}/></div>}</Section>
 <Section title="三、二次创作观看与参与"><p className="hint">二次创作包括基于已有动画、漫画、游戏、小说、角色或世界观进行的再创作内容。</p><Radio label="14. 你是否观看过二次元相关二次创作内容？" value={data.watch} onChange={v=>set('watch',v)} options={['经常观看','偶尔观看','看过几次','听说过但没看过','完全不了解']} />{['经常观看','偶尔观看','看过几次'].includes(data.watch)&&<div className="conditional"><Checks label="15. 你通常观看哪些类型的二次创作？（可多选）" items={checkGroups.fanTypes} group="fanTypes" data={data} toggle={toggle}/><Radio label="16. 观看二创的频率" value={data.watchFreq} onChange={v=>set('watchFreq',v)} options={['每天','每周数次','每周一次左右','每月数次','偶尔','几乎不看']}/><Checks label="17. 你通常在哪里观看二次创作？（可多选）" items={checkGroups.platforms} group="platforms" data={data} toggle={toggle}/><Checks label="18. 观看二创的主要目的（最多选5项）" items={['延续对原作的兴趣','更深入了解喜欢的角色','寻找原作中没有的内容','获得娱乐和放松','寻找情绪安慰','与其他粉丝交流','参与热门话题','了解圈内评价','获取创作灵感','支持喜欢的创作者']} group="watchReasons" data={data} toggle={toggle}/><Checks label="19. 观看二创时通常会进行哪些互动？（可多选）" items={checkGroups.interactions} group="interactions" data={data} toggle={toggle}/></div>}<Radio label="20. 你是否制作过二次创作内容？" value={data.create} onChange={v=>set('create',v)} options={['经常制作','偶尔制作','曾经制作过','有想法但没有实施','从未制作过']}/>{data.create&&data.create!=='从未制作过'&&<div className="conditional"><Checks label="21. 你制作过哪些类型的二创？（可多选）" items={checkGroups.createTypes} group="createTypes" data={data} toggle={toggle}/><Checks label="22. 你制作二创的主要动机（可多选）" items={checkGroups.motivations} group="motivations" data={data} toggle={toggle}/></div>}</Section>
 <Section title="四、二次元重要性"><p className="hint">以下题目请按实际情况选择：1=非常不同意，5=非常同意。</p>{importanceGroups.map(([title,items])=><div className="matrix-group" key={title}><h3>{title}</h3>{items.map((q,i)=><div className="matrix-row" key={q}><span>{q}</span><div className="scale">{scale.map((s,j)=><label key={s}><input type="radio" name={`q-${title}-${i}`} value={j+1} checked={data.importance[q]===j+1} onChange={()=>setData(d=>({...d,importance:{...d.importance,[q]:j+1}}))}/><b>{j+1}</b><small>{s}</small></label>)}</div></div>)}</div>)}<Textarea label="23. 如果用一句话描述二次元对你的重要性，你会如何描述？" value={data.importantText} onChange={v=>set('importantText',v)}/><Radio label="24. 如果未来只能保留二次元的一项内容，你最希望保留什么？" value={data.keep} onChange={v=>set('keep',v)} options={['作品观看和阅读','喜欢的角色','二次创作','二次元社群','线下活动','创作与表达','收藏与消费','其他']}/></Section>
 <button className="submit" type="submit">提交匿名问卷 ↗</button><p className="footer-note">提交即表示你同意以匿名方式参与本次社会调研。请勿填写真实姓名、联系方式等身份信息。</p></form></main>
}
function Section({title,children}){return <section className="survey-section"><div className="section-title"><span>✦</span><h2>{title}</h2></div>{children}</section>}
function Radio({label,options,value,onChange,required}){return <fieldset className="question"><legend>{label}{required&&<em> *</em>}</legend><div className="options">{options.map(o=><label key={o}><input required={required} type="radio" name={label} value={o} checked={value===o} onChange={()=>onChange(o)}/><span>{o}</span></label>)}</div></fieldset>}
function Checks({label,items,group,data,toggle}){return <fieldset className="question"><legend>{label}</legend><div className="options checks">{items.map(o=><label key={o}><input type="checkbox" checked={(data[group]||[]).includes(o)} onChange={()=>toggle(group,o)}/><span>{o}</span></label>)}</div></fieldset>}
function Input({label,value,onChange,placeholder}){return <label className="input-label">{label}<input value={value||''} onChange={e=>onChange(e.target.value)} placeholder={placeholder}/></label>}
function Textarea({label,value,onChange}){return <label className="input-label textarea-label">{label}<textarea value={value||''} onChange={e=>onChange(e.target.value)} rows="4"/></label>}
createRoot(document.getElementById('root')).render(<App/>)


